#ifndef QTBUILTINIMAGE_GLOBAL_H
#define QTBUILTINIMAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTBUILTINIMAGE_LIBRARY)
#  define QTBUILTINIMAGE_EXPORT Q_DECL_EXPORT
#else
#  define QTBUILTINIMAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // QTBUILTINIMAGE_GLOBAL_H
